export const texts = {
  tr: {
    language: "SWITCH TO",
    languageSub: " ENGLISH",
    skills: "Yetenekler",
    projects: "Projeler",
    hireMe: "Bana Ulaş",
    mainP: "Yaratıcı düşünür Minimalizm tutkunu",
    mainP2: "Merhaba, ben Atakan. Full-stack geliştiricisiyim. Üstün kullanıcı deneyimine sahip, sağlam ve ölçeklenebilir frontend ürünleri geliştirecek bir uzman arıyorsanız, sizinle iş birliği yapmaktan memnuniyet duyarım.",
    js: "Temel algoritmalar ve dinamik web sayfaları geliştirme konusunda JavaScript bilgisine sahibim.",
    react:"Bileşen tabanlı kullanıcı arayüzleri oluşturmak için React.js ile projeler geliştirdim.",
    spring:"Basit ve orta ölçekli backend servisleri geliştirmek için Spring Boot kullanımı konusunda deneyim kazandım.",
    profile:"Profil",
    birth:"Doğum Tarihi",
    place:"İkamet Şehri",
    edu:"Eğitim Durumu",
    prefer:"Tercih Ettiği Rol",
    licence:"Kocaeli Ünv. Kamu Yönetimi, \nLisans, 2018",
    about: "Hakkımda",
    aboutP1:"Yetenekli ve vizyoner bir Full Stack Developerım.Farklı sektörlerde boy gösterdikten sonra tutkum olan yazılım dünyasına giriş yaptım.Aldığım eğitimler ile JavaScript, Java, React, Redux, Cypress, NodeJs, Tailwind vb dillerde ve frameworkler de uzmanlaştım.Kendimi alanımda sürekli geliştirmeyi ve güncel tutmayı hedefliyorum. ",
    aboutP2:"Kısa vadede bu yeteneklerimi karşılıklı olarak geliştirebileceğim projelerde ve şirketlerde çalışmak istiyorum. Uzun vadede ise bilgi çağında parmak ile gösterilen, tam anlamıyla güncele uyum sağlamış ve geliştirmeye, hayal etmeye ne olursa olsun devam eden bir yazılımcı veya yazılımcılar yetiştiren bir yol gösterici olmak istiyorum.",
  },
  en: {
    language: "TÜRKÇE",
    languageSub: "'YE GEÇ",
    skills: "Skills",
    projects: "Projects",
    hireMe: "Hire Me",
    mainP:"Creative thinker Minimalism lover",
    mainP2:"Hi, I’m Atakan. I’m a full-stack developer. If you are looking for a developer who can craft solid and scalable frontend products with great user experiences, let’s shake hands with me.",
    js:"I have knowledge of JavaScript for developing basic algorithms and dynamic web pages.",
    react:"I have developed projects using React.js to build component-based user interfaces.",
    spring:"I have gained experience in using Spring Boot to develop simple and medium-scale backend services.",
    profile:"Profile",
    birth:"Date of Birth",
    place:"City of Residence",
    edu:"Educational Background",
    prefer:"Preferred Role",
    licence:"Kocaeli University, Public Adm. \nBachelor's Degree, 2018",
    about: "About Me",
    aboutP1:"I am a talented and visionary Full Stack Developer.After gaining experience in various sectors, I transitioned into the world of software development, which has always been my true passion.Through the training I have received, I have developed expertise in JavaScript, Java, React, Redux, Cypress, Node.js, Tailwind, and other related languages and frameworks.I am committed to continuously improving myself and staying up-to-date in my field.",
    aboutP2:"In the short term, I aim to work on projects and in companies where I can mutually develop and enhance my skills.In the long term, my goal is to become a well-recognized developer who fully adapts to the ever-evolving digital age, continually improves and dreams without limits, and eventually guides and mentors future developers.",
  }

};
